### ISSUE TITLE
Error: couldn't load maps/ntro.inn.bsp

### ISSUE THREAD

**Issue by Kzer-Za** [UCyborg/BerserkerQuake2#11]
I did everything according to the instruction. The engine can be launched but when I try to start the game (Game -> $difficulty), the console shows up with this error `Error: couldn't load maps/ntro.inn.bsp`. If I press the ~ to hide the console, a demo starts playing. In the demo everything looks fine, without any issues, everything is working: graphics, sound, music.

I'm on Linux, `berserkerq2` is in the main game folder, `game.so` is in the `baseq2` subfolder.

**Comment by UCyborg** [comment]
I updated the engine with a patch for this issue, it should work now.

**Comment by Kzer-Za** [comment]
Wow, that was fast! :) Thanks!
